global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'delivery_service'
    static_configs:
      - targets: ['delivery_service:9101']
        labels:
          service: 'delivery_service'
          env: 'development'

  - job_name: 'bonus_service'
    static_configs:
      - targets: ['bonus_service:9102']
        labels:
          service: 'bonus_service'
          env: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']