name: Delivery Service CI/CD to Yandex Cloud

on:
  push:
    branches: ["main"]
    paths:
      - 'delivery_service/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'delivery_service/**'

jobs:
  build-and-push-to-yc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build ./delivery_service --file ./delivery_service/Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest
          docker tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:${{ github.sha }}

      - name: Login to YC Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push to YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:${{ github.sha }}

  deploy:
    name: Deploy to Serverless Container
    runs-on: ubuntu-latest
    needs: build-and-push-to-yc

    steps:
      - name: Configure YC CLI
        uses: yc-actions/yc-setup@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}

      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-env: |
            AMQP_URL=${{ secrets.ENV_AMQP_URL }}
            POSTGRES_URL=${{ secrets.ENV_POSTGRES_URL }}